# Generated by Django 4.1.5 on 2023-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=32)),
                ('antiguedad', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=30)),
            ],
        ),
    ]
